version: '3.7'
services:
  redis:
    image: 'redis:5-alpine'
  wallet-connect-bridge:
    image: 'arianeetech/node-walletconnect-bridge'
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - 5001:5001
