version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ./common_steps
          paths:
            - "*"
  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: ./common_steps
      - run:
          name: tests
          command: npm run test


workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
