version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build application (node)
          command: npm run build
      - persist_to_workspace:
          root: ./common_steps
          paths:
            - "*"

  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: ./common_steps
      - run:
          name: Run Test(s)
          command: npm run test

  deploy: 
    docker: 
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - attach_workspace:
          at: ./common_steps
      - run: 
          name: Auth With NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish

  push-github:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - attach_workspace:
          at: ./common_steps
      - add_ssh_keys:
          fingerprints:
            - "a9:f1:db:7a:fa:cf:ed:6c:2f:4b:f4:80:08:ae:8a:06"
      - run:
          name: Publish new version to Github
          command: npm run postpublish

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-approval:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - deploy-approval
      - push-github:
          requires:
            - deploy
