version: 2.1

orbs:
  node: circleci/node@5.0.2
  gh: circleci/github-cli@2.1.0

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build application (node)
          command: npm run build
      - persist_to_workspace:
          root: ./common_steps
          paths:
            - "*"

  test:
    machine:
      image: ubuntu-2204:2024.05.1
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: ./common_steps
      - run:
          name: Run Test(s)
          command: npm run test
      - persist_to_workspace:
          root: ./common_steps
          paths:
            - "*"

  deploy-npm:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: ./common_steps
      - run:
          name: Auth With NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to NPM
          command: npm publish --ignore-scripts

  deploy-gh-release:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - gh/setup:
          version: 2.14.3
      - run:
          name: Create Github Release
          command: |
            gh release create v$(grep '"version": "' package.json | cut -d '"' -f4) --generate-notes

  push-github:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - attach_workspace:
          at: ./common_steps
      - add_ssh_keys:
          fingerprints:
            - "a9:f1:db:7a:fa:cf:ed:6c:2f:4b:f4:80:08:ae:8a:06"
      - run:
          name: Config Github account
          command: |
            git config user.name "Package Version Bot"
            git config user.email "tech@arianee.org"
      - run:
          name: Publish new version to Github
          command: npm run postpublish

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-npm-approval:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy-release-approval:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy-gh-release:
          requires:
            - deploy-release-approval
      - deploy-npm:
          requires:
            - deploy-npm-approval
      - push-github:
          requires:
            - deploy-npm
